basePath: /api/events/v1
definitions:
  entities.Event:
    properties:
      active:
        type: boolean
      canceled:
        type: boolean
      date:
        type: string
      deleted:
        type: boolean
      description:
        type: string
      embeddings:
        items:
          type: number
        type: array
      id:
        type: integer
      image_url:
        type: string
      location:
        type: string
      name:
        type: string
      photo:
        type: string
      suspended:
        type: boolean
    type: object
  http.ErrorResponse:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  http.GetEventsResponse:
    properties:
      last_participated_events:
        items:
          $ref: '#/definitions/entities.Event'
        type: array
      recommended_events:
        items:
          $ref: '#/definitions/entities.Event'
        type: array
      subscribed_events:
        items:
          $ref: '#/definitions/entities.Event'
        type: array
      trending_events:
        items:
          $ref: '#/definitions/entities.Event'
        type: array
    type: object
  services.CancelEventServiceOutput:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  services.CancelSubscriptionServiceOutput:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  services.ConfirmSubscriptionOutput:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  services.CreateEventServiceOutput:
    properties:
      event_id:
        type: integer
      message:
        type: string
      status_code:
        type: integer
    type: object
  services.GetConfirmationCodeOutput:
    properties:
      code:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  services.SubscribeEventServiceOutput:
    properties:
      code:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: This is the API for the Events Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Events Service API
  version: "1.0"
paths:
  /cancel-subscription/{id}:
    post:
      consumes:
      - application/json
      description: Cancel a subscription to an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: header
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.CancelSubscriptionServiceOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.CancelSubscriptionServiceOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/services.CancelSubscriptionServiceOutput'
      security:
      - Bearer: []
      summary: Cancel a subscription to an event
      tags:
      - events
  /cancel/{id}:
    patch:
      consumes:
      - application/json
      description: Cancel an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.CancelEventServiceOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.CancelEventServiceOutput'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/services.CancelEventServiceOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.CancelEventServiceOutput'
      security:
      - Bearer: []
      summary: Cancel an event
      tags:
      - events
  /confirm-subscription/{id}:
    post:
      consumes:
      - application/json
      description: Confirm a subscription to an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: header
        name: userId
        required: true
        type: integer
      - description: Confirmation code
        in: body
        name: code
        required: true
        schema:
          properties:
            code:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ConfirmSubscriptionOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.ConfirmSubscriptionOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/services.ConfirmSubscriptionOutput'
      security:
      - Bearer: []
      summary: Confirm a subscription to an event
      tags:
      - events
  /confirmation-code/{id}:
    get:
      consumes:
      - application/json
      description: Get a confirmation code for an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: header
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.GetConfirmationCodeOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.GetConfirmationCodeOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/services.GetConfirmationCodeOutput'
      security:
      - Bearer: []
      summary: Get a confirmation code for an event
      tags:
      - events
  /create:
    post:
      consumes:
      - multipart/form-data
      description: Create an event
      parameters:
      - description: Event image
        in: formData
        name: image
        required: true
        type: file
      - description: Event name
        in: formData
        name: name
        required: true
        type: string
      - description: Event description
        in: formData
        name: description
        type: string
      - description: Event date
        in: formData
        name: date
        required: true
        type: string
      - description: Event location
        in: formData
        name: location
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/services.CreateEventServiceOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.CreateEventServiceOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.CreateEventServiceOutput'
      security:
      - Bearer: []
      summary: Create an event
      tags:
      - events
  /events:
    get:
      consumes:
      - application/json
      description: Get recommended, trending, last participated and subscribed events
        for the authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.GetEventsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      security:
      - Bearer: []
      summary: Get events
      tags:
      - events
  /subscribe/{id}:
    post:
      consumes:
      - application/json
      description: Subscribe to an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: header
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.SubscribeEventServiceOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.SubscribeEventServiceOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/services.SubscribeEventServiceOutput'
      security:
      - Bearer: []
      summary: Subscribe to an event
      tags:
      - events
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
